on: [push]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
    run: |
      echo This demo file shows a 
      echo very basic and easy-to-understand workflow.
      echo ${GITHUB_TOKEN}
